#!/usr/bin/env bash
set -eu

if [[ $GITHUB_REF_NAME != "main" ]]
then
  exit 0
fi

message_to_send() {
  SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-8)
  cat <<EOF
{
    "msgtype": "markdown",
    "markdown": {
        "content": "Ooops!! The pipeline failed. \n
         >commit id: <font color=\"comment\">[$SHORT_SHA](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)</font>
         >repository: <font color=\"comment\">$GITHUB_REPOSITORY</font>
         >branch: <font color=\"comment\">$GITHUB_REF_NAME</font>
         >person: <font color=\"comment\">$GITHUB_ACTOR</font>
         >message: <font color=\"comment\">$MESSAGE</font>\n
         \nYou can check it here [failed pipeline](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
    }
}
EOF
}

export WEBHOOK_URL
curl -X POST \
  -H "Content-Type: application/json" \
  -d "$(message_to_send)" \
  --url "$WEBHOOK_URL"
