name: push images to ECR

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  ECR-task:
    name: Build image and push to ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-east-1'
          role-to-assume: 'arn:aws:iam::494526681395:role/xr-github-test'

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: 'xinrui/demo'
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: send-failure-message
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        if: ${{ failure() }}
        run: ./auto/send_message
